image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo ${MAVEN_SETTINGS} | base64 -d > settings.xml
    - mvn -s settings.xml clean install deploy
